/* The Data & Decision Audit Report.

   Rendered from the generated audit, which is derived from the same payload
   every other page reads. Nothing is asserted here that the build did not
   already establish, so this page cannot drift from the figures it rates.

   The five sections are kept apart on purpose: a conclusion can carry a
   warning while every source beneath it passes, and collapsing them into one
   score would hide exactly that. */
(function (global) {
  'use strict';

  const DA = global.DataAccess, U = global.UI;
  const $ = function (s, r) { return (r || document).querySelector(s); };

  const TONE = { PASS: 'pass', WARNING: 'warning', FAIL: 'fail',
                 BLOCKED: 'blocked' };

  function pill(rating, n) {
    if (!n) return '';
    return '<span class="au-pill au-' + TONE[rating] + '">' +
      n + ' ' + rating.toLowerCase() + '</span>';
  }

  function counts(c) {
    return ['FAIL', 'BLOCKED', 'WARNING', 'PASS']
      .map(function (r) { return pill(r, c[r]); }).join('');
  }

  function row(e) {
    return '<tr class="au-row au-' + TONE[e.rating] + '">' +
      '<td class="au-rating"><span class="au-dot"></span>' +
        U.esc(e.rating) + '</td>' +
      '<td><div class="au-title">' + U.esc(e.title) + '</div>' +
        (e.basis ? '<div class="au-basis">' + U.esc(e.basis) + '</div>' : '') +
        (e.limitation ? '<div class="au-lim">' + U.esc(e.limitation) + '</div>' : '') +
        (e.clears ? '<div class="au-clears"><strong>Would clear it:</strong> ' +
          U.esc(e.clears) + '</div>' : '') +
      '</td></tr>';
  }

  function render(host) {
    const a = DA.getAudit();
    if (!a) {
      host.innerHTML = U.emptyState('Not available',
        'The audit is generated by the build; no audit is present in this payload.');
      return;
    }

    let h = '<header class="page-head"><h1>Data &amp; decision audit</h1>' +
      '<p class="q">Every source, measure, mapping, conclusion and management ' +
      'insight, rated on what holds it up.</p></header>';

    h += '<section class="home-hero"><span class="label">Audit summary · ' +
      'parser ' + U.esc(a.parser_version || '?') + '</span>' +
      '<h1>' + a.total + ' items rated' +
      (a.failed.length ? ', ' + a.failed.length + ' failing' : ', none failing') +
      '</h1>' +
      '<p class="lede">' + U.esc(a.note) + '</p>' +
      '<div class="home-figs">' +
      ['PASS', 'WARNING', 'BLOCKED', 'FAIL'].map(function (r, i) {
        return '<div class="home-fig' + (i === 0 ? ' lead' : '') + '">' +
          '<div class="v">' + (a.counts[r] || 0) + '</div>' +
          '<div class="k">' + r.toLowerCase() + '</div></div>';
      }).join('') + '</div></section>';

    if (a.blocked.length) {
      h += '<section class="sec"><div class="sec-head"><h2>What cannot be built' +
        '</h2><span class="sub">Each with the input that would clear it</span>' +
        '</div><div class="card"><div class="tbl-wrap"><table><tbody>' +
        a.blocked.map(row).join('') + '</tbody></table></div></div></section>';
    }

    a.sections.forEach(function (s) {
      if (!s.entries.length) return;
      h += '<section class="sec"><div class="sec-head"><h2>' + U.esc(s.title) +
        '</h2><span class="sub">' + U.esc(s.question) + '</span></div>' +
        '<div class="au-counts">' + counts(s.counts) + '</div>' +
        '<div class="card" style="margin-top:10px"><div class="tbl-wrap">' +
        '<table><tbody>' + s.entries.map(row).join('') +
        '</tbody></table></div></div></section>';
    });

    host.innerHTML = h;
    U.observeReveals(host);
  }

  global.AuditReport = { render: render };
})(window);
